force-app/main/default/objects/BackendTransaction__c/BackendTransaction__c.object-meta.xml
<CustomObject>
    <label>Backend Transaction</label>
    <nameField>
        <label>BackendTransaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Backend Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BackendTransaction__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Backend Transactions</relationshipLabel>
    <relationshipName>Backend_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BackendTransaction__c/fields/Loan_Name__c.field-meta.xml
<CustomField>
    <fullName>Loan_Name__c</fullName>
    <label>Loan Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BackendTransaction__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BackendTransaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Succeeded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BackendTransaction__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>StatusCode</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BackendTransactionLogger.cls
public class BackendTransactionLogger {
    public static void logTransaction(String operation, String statusCode, String message, Id loanRecordId, String loanName) {
        String status = statusCode == '200' ? 'Succeeded' : 'Failed';

        BackendTransaction__c log = new BackendTransaction__c(
            Operation__c = operation,
            Status__c = status,
            StatusCode__c = statusCode,
            Message__c = message,
            Loan__c = loanRecordId,
            Loan_Name__c = loanName
        );
        insert log;
    }
}